### ISSUE TITLE
Namespace is not replaced in PHP tests

### ISSUE THREAD

**Issue by AlexSkrypnyk** [AlexSkrypnyk/scaffold#61]
`init.sh` does not replace a namespace in the PHP tests.

**Comment by tannguyen04** [comment]
From @AlexSkrypnyk 

> I'm checking this test and it looks like it is working and is covered
> ---------
> https://github.com/AlexSkrypnyk/scaffold/blob/main/tests/scaffold/_assert_init.bash#L83
> And this coverage report confirms that this is working
> https://app.codecov.io/gh/AlexSkrypnyk/scaffold/blob/main/init.sh#L233
> ---------
> Please copy the above to the ticket and close it. thanks

**Comment by tannguyen04** [comment]
From @AlexSkrypnyk 
```
I'm checking this test and it looks like it is working and is covered
---------
https://github.com/AlexSkrypnyk/scaffold/blob/main/tests/scaffold/_assert_init.bash#L83
And this coverage report confirms that this is working
https://app.codecov.io/gh/AlexSkrypnyk/scaffold/blob/main/init.sh#L233
---------
Please copy the above to the ticket and close it. thanks
```
